export const FETCHPRODUCTDATA = "FETCHPRODUCTDATA";
export const ISLOADING = "ISLOADING";
export const ISERROR = "ISERROR";

export const UPPERFILTER = "UPPERFILTER";

export const CHANGEVARIANTCOLOR = "CHANGEVARIANTCOLOR";

export const UPDATEDATAWITHFILTER = "UPDATEDATAWITHFILTER";
