export const products = [
  {
    id: 1,
    category: "Shorts",
    img: "https://www.jcrew.com/s7-img-facade/BF105_BR6565?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    colors: ["blue", "white", "black"],
    size: ["s", "m", "l", "xl"],
    Trending: "best_seller",
    brand: "canvas",
    price: 8000,
    title: "Indian madras shirt in cotton",
  },
  {
    id: 2,
    category: "Shorts",
    img: "https://www.jcrew.com/s7-img-facade/BE052_WZ2044?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    colors: ["blue", "white", "black", "yellow"],
    size: ["s", "m", "l", "xl"],
    Trending: "best_seller",
    brand: "canvas",
    price: 12000,
    title: "9 stretch chino short",
  },
  {
    id: 3,
    category: "Shorts",
    img: "https://www.jcrew.com/s7-img-facade/BF105_BR6565?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    colors: ["blue", "white", "black", "yellow", "green", "white"],
    size: ["s", "m", "l", "xl"],
    Trending: "top_rated",
    brand: "canvas",
    price: 12000,
    title: "9 stretch chino short",
  },
  {
    id: 4,
    category: "Shorts",
    img: "https://www.jcrew.com/s7-img-facade/BG268_BL7780?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    colors: ["pink", "blue"],
    size: ["small", "medium", "Large"],
    Trending: "best_seller",
    brand: "canvas",
    price: 8921,
    title: "7 Irish linen lounge short",
  },
  {
    id: 5,
    category: "Shorts",
    img: "https://www.jcrew.com/s7-img-facade/BF105_BR6565?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    colors: ["light_blue", "blue", "black", "yellow"],
    size: ["small", "medium", "Large"],
    Trending: "best_seller",
    brand: "canvas",
    price: 8912,
    title: "5 stretch chino short",
  },
  {
    id: 6,
    category: "Shorts",
    img: "https://www.jcrew.com/s7-img-facade/BE050_OR6170?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    colors: ["yellow", "pink", "black", "white", "gray"],
    size: ["small", "medium", "Large"],
    Trending: "top_rated",
    brand: "canvas",
    price: 8912,
    title: "5 stretch chino short",
  },
  {
    id: 7,
    category: "Shorts",
    img: "https://www.jcrew.com/s7-img-facade/BE051_BL7527?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    colors: ["light_blue", "blue", "black", "white", "gray"],
    size: ["small", "medium", "Large"],
    Trending: "top_rated",
    brand: "canvas",
    price: 8912,
    title: "7 stretch chino short",
  },
  {
    id: 8,
    category: "Shorts",
    img: "https://www.jcrew.com/s7-img-facade/BE051_WZ2044?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    colors: ["blue", "black", "white", "gray"],
    size: ["small", "medium", "Large"],
    Trending: "top_rated",
    brand: "canvas",
    price: 8912,
    title: "7 stretch chino short",
  },
  {
    id: 9,
    category: "Shorts",
    img: "https://www.jcrew.com/s7-img-facade/BE052_BL7527?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    colors: ["light_blue", "black", "white", "gray"],
    size: ["small", "medium", "Large"],
    Trending: "top_rated",
    brand: "canvas",
    price: 8912,
    title: "9 stretch chino short",
  },
  {
    id: 10,
    category: "Shorts",
    img: "https://www.jcrew.com/s7-img-facade/BG937_WZ2023?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    colors: ["light_blue", "black", "white", "gray"],
    size: ["small", "medium", "Large"],
    Trending: "best_seller",
    brand: "canvas",
    price: 8912,
    title: "6 dock short in windowpane check",
  },
  {
    id: 11,
    category: "Shorts",
    img: "https://www.jcrew.com/s7-img-facade/BG937_WZ2024?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    colors: ["yellow", "black", "white", "gray"],
    size: ["small", "medium", "Large"],
    Trending: "best_seller",
    brand: "canvas",
    price: 8912,
    title: "6 dock short in windowpane check",
  },
  {
    id: 12,
    category: "Shorts",
    img: "https://www.jcrew.com/s7-img-facade/BG939_PT1397?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    colors: ["yellow", "black", "white", "gray"],
    size: ["small", "medium", "Large"],
    Trending: "best_seller",
    brand: "canvas",
    price: 8912,
    title: "6 dock short in floral print",
  },
];
